version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_8.0
    environment:
      MYSQL_DATABASE: exam
      MYSQL_ROOT_PASSWORD: 1234
      DB_USERNAME: root
      DB_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    healthcheck:
      test: ["CMD-SHELL", "MYSQL_PWD=${DB_PASSWORD} mysql -h localhost -u${DB_USERNAME} -e 'SELECT NOW();'"]
      interval: 10s
      timeout: 5s
      retries: 5